// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzK8_uCMp1siY35nTO44MNX3SuOXSzZUM',
    appId: '1:698169034813:web:c5a5566d2ab9b00d1a0254',
    messagingSenderId: '698169034813',
    projectId: 'uas-softdev',
    authDomain: 'uas-softdev.firebaseapp.com',
    databaseURL: 'https://uas-softdev-default-rtdb.firebaseio.com',
    storageBucket: 'uas-softdev.appspot.com',
    measurementId: 'G-W6Y96HLMBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFllKKtkLLSfqLDfdxOkNqlLM2avnFxNw',
    appId: '1:698169034813:android:dd2f5d2e989d6fa71a0254',
    messagingSenderId: '698169034813',
    projectId: 'uas-softdev',
    databaseURL: 'https://uas-softdev-default-rtdb.firebaseio.com',
    storageBucket: 'uas-softdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9gbO6sLCe6YHZDIqhb-xr9CZFHppFIo',
    appId: '1:698169034813:ios:a3a05adf8f347a1c1a0254',
    messagingSenderId: '698169034813',
    projectId: 'uas-softdev',
    databaseURL: 'https://uas-softdev-default-rtdb.firebaseio.com',
    storageBucket: 'uas-softdev.appspot.com',
    iosClientId: '698169034813-o9jjbcejf7lo822vmirgv50ml66luf88.apps.googleusercontent.com',
    iosBundleId: 'com.example.cekongkir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9gbO6sLCe6YHZDIqhb-xr9CZFHppFIo',
    appId: '1:698169034813:ios:8ffba13232aa0e171a0254',
    messagingSenderId: '698169034813',
    projectId: 'uas-softdev',
    databaseURL: 'https://uas-softdev-default-rtdb.firebaseio.com',
    storageBucket: 'uas-softdev.appspot.com',
    iosClientId: '698169034813-g85ruam9a54l7hqcklt79aruabu51nct.apps.googleusercontent.com',
    iosBundleId: 'com.example.cekongkir.RunnerTests',
  );
}
